name: Linux - Build QI-QMP (Qt 6.3.1)
on:
  workflow_call:
    secrets:
      qt_shared_dec_key:
        description: 'MEGA decryption key for Qt shared install archive URL'
        required: true
      qt_static_dec_key:
        description: 'MEGA decryption key for Qt static install archive URL'
        required: true
    outputs:
      qt_shared_artifact_name:
        description: "QI-QMP (Qt shared) build artifact"
        value: ${{ jobs.build-qi-qmp.outputs.qt_shared_artifact_name }}
      qt_static_artifact_name:
        description: "QI-QMP (Qt static) build artifact"
        value: ${{ jobs.build-qi-qmp.outputs.qt_static_artifact_name }}
env:
  general_download_dir: ${{ github.workspace }}/Download
  qt_install_dir: ${{ github.workspace }}/Qt/Install
  qt_download_dir: ${{ github.workspace }}/Qt/Download
  qi-qmp_src_suffix: QI-QMP/Source
  qi-qmp_src_dir: ${{ github.workspace }}/QI-QMP/Source
  qi-qmp_build_dir: ${{ github.workspace }}/QI-QMP/Build

jobs:
  build-qi-qmp:
    name: Build QI-QMP - Linux (Debug/Release)
    strategy:
      matrix:
        qt_linkage: [shared, static]
    runs-on: ubuntu-latest
    env:
      c_comp: clang
      cxx_comp: clang++
      cmake_gen: Ninja Multi-Config
    outputs:
      qt_shared_artifact_name: ${{ steps.get_artifact_name.outputs.qt_shared_artifact_name }}
      qt_static_artifact_name: ${{ steps.get_artifact_name.outputs.qt_static_artifact_name }}
    steps:
    - name: Set matrix derived variables
      uses: kanga333/variable-mapper@v0.2.2
      with:
        key: ${{ matrix.qt_linkage }}
        map: |
          {
            "shared": {
              "qt_install_name": "qt-Production-6.3.1-linux-clang-x64-shared-release.7z",
              "qt_install_url": "https://mega.nz/file/NiIEAITC",
              "qt_install_url_key": "${{ secrets.qt_shared_dec_key }}",
              "artifact_output_var": "qt_shared_artifact_name"
            },
            "static": {
              "qt_install_name": "qt-Production-6.3.1-linux-clang-x64-static-release.7z",
              "qt_install_url": "https://mega.nz/file/VjJ2CR4R",
              "qt_install_url_key": "${{ secrets.qt_static_dec_key }}",
              "artifact_output_var": "qt_static_artifact_name"
            }
          }
        export_to: env,log
    - name: Set derived variables with shell because GitHub Actions env context sucks
      run: |
        echo "qt_install_dest=${{ env.qt_download_dir }}/${{ env.qt_install_name }}" >> $GITHUB_ENV
        echo "qi-qmp_package_path=${{ env.qi-qmp_build_dir }}/out/dist" >> $GITHUB_ENV
        qi-qmp_install_path="${{ env.qi-qmp_build_dir }}/out/install"
        echo "qi-qmp_install_path=$qi-qmp_install_path" >> $GITHUB_ENV
        echo "qt_cmake=$qt_install_dir/bin/qt-cmake" >> $GITHUB_ENV
    - name: Cache Qt Build
      id: cache-qt
      uses: actions/cache@v3
      with:
        path: ${{ env.qt_install_dir }}
        key: ${{ env.qt_install_name }}
    - name: Install megatools
      if: steps.cache-qt.outputs.cache-hit != 'true'
      env:
        mt_build: megatools-1.11.0.20220519-linux-x86_64
        mt_arch_ext: tar.gz
        mt_repo: https://megatools.megous.com/builds/builds/
      run: |
        curl "$mt_repo/$mt_build.$mt_arch_ext" --output "$general_download_dir/$mt_build.$mt_arch_ext" --create-dirs --location --silent --show-error
        cd $general_download_dir
        tar xf "$mt_build.$mt_arch_ext"
        cd "$mt_build"
        cp -p megatools /usr/local/bin
    - name: Create Qt Download Directory
      if: steps.cache-qt.outputs.cache-hit != 'true'
      run: mkdir -p "${{ env.qt_download_dir }}"
    - name: Download Qt Install
      if: steps.cache-qt.outputs.cache-hit != 'true'
      run: megatools dl "$qt_install_url#$qt_install_url_key" --path "${{ env.qt_download_dir }}"
    - name: Extract Qt Install
      if: steps.cache-qt.outputs.cache-hit != 'true'
      run: 7z x ${{ env.qt_install_dest }} -o${{ env.qt_install_dir }}
    - name: Set clang-12 as preferred
      run: |
        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-12 100
        sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-12 100
        sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-12 100
    - name: Install OpenGL lib
      run: sudo apt-get install libglu1-mesa-dev
    - name: Install XCB-XKB
      run: sudo apt-get install libxkbcommon-dev libxcb-xkb-dev
    - name: Install Doxygen
      env:
        doxy_build: doxygen-1.9.4
        doxy_arch_ext: linux.bin.tar.gz
        doxy_repo: https://www.doxygen.nl/files
      run: |
        curl "$doxy_repo/$doxy_build.$doxy_arch_ext" --output "$general_download_dir/$doxy_build.$doxy_arch_ext" --create-dirs --location --silent --show-error
        cd $general_download_dir
        tar xf "$doxy_build.$doxy_arch_ext"
        cd "$doxy_build"
        sudo make install
    - name: Install Graphviz
      run: sudo apt-get install graphviz
    - name: Install Ninja
      run: sudo apt-get install ninja-build
    - name: Checkout QI-QMP
      uses: actions/checkout@v3
      with:
        path: ${{ env.qi-qmp_src_suffix }}
        fetch-depth: 0 # Required for verbose versioning to work correctly
    - name: Build/Install QI-QMP
      working-directory: ${{ env.qi-qmp_src_dir }}
      run: |
        echo Configuring CMake...
        "$qt_cmake" -G "$cmake_gen" -S "$qi-qmp_src_dir" -B "$qi-qmp_build_dir" -D QI_QMP_DOCS_TARGET=ON -D CMAKE_CXX_COMPILER="$cxx_comp" -D CMAKE_C_COMPILER="$c_comp"
        echo Changing to build directory...
        cd "$qi-qmp_build_dir"
        echo Building QI-QMP debug...
        cmake --build . --target all --config Debug
        echo Building QI-QMP release...
        cmake --build . --target all --config Release
        echo Building QI-QMP docs...
        cmake --build . --target qi_qmp_docs --config Release
        echo Installing QI-QMP Debug
        cmake --build . --target install --config Debug
        echo Installing QI-QMP Release/Docs...
        cmake --build . --target install --config Release
        echo Packaging QI-QMP...
        cpack -C "Debug;Release"
        echo Build complete.
    - name: Get QI-QMP artifact name
      id: get_artifact_name
      run: |
        cpack_name=$(find * -type f -name "*.zip")
        artifact_name=$(basename "$cpack_name" .zip)
        echo "::set-output name=${{ env.artifact_output_var }}::$artifact_name"
    - name: Upload QI-QMP build artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.get_artifact_name.outputs[env.artifact_output_var] }}
        path: ${{ env.qi-qmp_install_path }}
        if-no-files-found: error
