name: Linux - Build QI-QMP
on:
  workflow_call:
    secrets:
      qt_ffynnon_cred:
        description: 'Credentials for getting Qt from Ffynnon'
        required: true
env:
  general_download_dir: ${{ github.workspace }}/Download
  qt_install_dir: ${{ github.workspace }}/Qt/Install
  qi_qmp_src_suffix: QI-QMP/Source
  qi_qmp_src_dir: ${{ github.workspace }}/QI-QMP/Source
  qi_qmp_build_dir: ${{ github.workspace }}/QI-QMP/Build

jobs:
  build-qi-qmp:
    name: Build QI-QMP - Linux (Debug/Release)
    strategy:
      matrix:
        qt_linkage: [shared, static]
    runs-on: ubuntu-20.04
    env:
      c_comp: clang-12
      cxx_comp: clang++-12
      cmake_gen: Ninja Multi-Config
    steps:
    - name: Set derived variables with shell because GitHub Actions env context sucks
      run: |
        echo "qi_qmp_package_path=${{ env.qi_qmp_build_dir }}/out/dist" >> $GITHUB_ENV
        qi_qmp_install_path="${{ env.qi_qmp_build_dir }}/out/install"
        echo "qi_qmp_install_path=$qi_qmp_install_path" >> $GITHUB_ENV
        echo "qt_cmake=$qt_install_dir/bin/qt-cmake" >> $GITHUB_ENV
    - name: Install Qt (custom build)
      uses: oblivioncth/actions/general/install-and-cache-qt-from-ffynnon@dev
      with:
        version: 6.4.0
        os: linux
        compiler: clang
        linkage: ${{ matrix.qt_linkage }}
        path: ${{ env.qt_install_dir }}
        credentials: ${{ secrets.qt_ffynnon_cred }}
    - name: Install OpenGL lib
      run: sudo apt-get install libglu1-mesa-dev
    - name: Install XCB Related libs
      run: sudo apt-get install libx11-xcb-dev libxkbcommon-dev libxkbcommon-x11-dev libxcb-*-dev
    - name: Install Doxygen
      uses: oblivioncth/actions/ubuntu/install-doxygen-from-sourceforge@dev
      with:
        version: 1.9.4
    - name: Install Graphviz
      run: sudo apt-get install graphviz
    - name: Install Ninja
      run: sudo apt-get install ninja-build
    - name: Install Harfbuzz
      run: sudo apt-get install libharfbuzz-dev
    - name: Checkout QI-QMP
      uses: actions/checkout@v3
      with:
        path: ${{ env.qi_qmp_src_suffix }}
        fetch-depth: 0 # Required for verbose versioning to work correctly
    - name: Build/Install QI-QMP
      working-directory: ${{ env.qi_qmp_src_dir }}
      run: |
        echo Configuring CMake...
        "$qt_cmake" -G "$cmake_gen" -S "$qi_qmp_src_dir" -B "$qi_qmp_build_dir" -D QI_QMP_DOCS_TARGET=ON -D CMAKE_CXX_COMPILER="$cxx_comp" -D CMAKE_C_COMPILER="$c_comp"
        echo Changing to build directory...
        cd "$qi_qmp_build_dir"
        echo Building QI-QMP debug...
        cmake --build . --target all --config Debug
        echo Building QI-QMP release...
        cmake --build . --target all --config Release
        echo Building QI-QMP docs...
        cmake --build . --target qi_qmp_docs --config Release
        echo Installing QI-QMP Debug
        cmake --build . --target install --config Debug
        echo Installing QI-QMP Release/Docs...
        cmake --build . --target install --config Release
        echo Packaging QI-QMP...
        cpack -C "Debug;Release"
        echo Build complete.
    - name: Get QI-QMP artifact name
      id: get_artifact_name
      run: |
        cpack_name=$(find "${{ env.qi_qmp_package_path }}" -type f -name "*.zip")
        artifact_name=$(basename "$cpack_name" .zip)
        echo "current_artifact_name=$artifact_name" >> $GITHUB_ENV
    - name: Upload QI-QMP build artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.current_artifact_name }}
        path: ${{ env.qi_qmp_install_path }}
        if-no-files-found: error
