name: QI-QMP Push Reaction
on:
  workflow_dispatch:
  push:
    branches-ignore:
    - 'master'

jobs:
  trigger-windows-build:
    name: Build QI-QMP (Windows)
    uses: ./.github/workflows/build-qi-qmp-windows.yml
    secrets:
      qt_shared_url: ${{ secrets.QT_WINDOWS_SHARED_URL }}
      qt_static_url: ${{ secrets.QT_WINDOWS_STATIC_URL }}
   
  trigger-linux-build:
      name: Build QI-QMP (Linux)
      uses: ./.github/workflows/build-qi-qmp-linux.yml
      secrets:
        qt_shared_url: ${{ secrets.QT_LINUX_SHARED_URL }}
        qt_static_url: ${{ secrets.QT_LINUX_STATIC_URL }}   