name: QI-QMP Push Reaction
on:
  workflow_dispatch:
  push:
    branches-ignore:
    - 'master'

jobs:
  trigger-windows-build:
    name: Build QI-QMP (Windows)
    uses: ./.github/workflows/build-qi-qmp-windows.yml
    secrets:
      qt_ffynnon_cred: ${{ secrets.OBYBOT_FFYNNON_CREDS }}
   
  trigger-linux-build:
    name: Build QI-QMP (Linux)
    uses: ./.github/workflows/build-qi-qmp-linux.yml
    secrets:
      qt_ffynnon_cred: ${{ secrets.OBYBOT_FFYNNON_CREDS }}